name: Python Tests

on: 
  push:
    branches:
      - main  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13' 

    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv 

    - name: Install dependencies
      run: |
        run: uv sync --all-extras --dev

    - name: Run tests
      run: |
        python -m unittest discover  
