name: Python Tests

on: 
  push:
    branches:
      - main  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        run: uv sync

    - name: Run tests
      run: |
        python -m unittest discover  
